[project]
name = "rewind"
version = "0.0.1"
description = "Disk-backed OBS replay buffer"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
  "obsws-python",
  "tomli-w",
  "watchdog",
  "tqdm"
]

[project.scripts]
rewind = "rewind.cli:main"
rewind-daemon = "rewind.daemon:main"

[tool.setuptools.package-data]
rewind = ["config.toml"]
